version: '3.8'

services:
  web:
    build: .
    command: gunicorn universidad.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/planetsuperheroes/staticfiles
    expose:
      - 8000
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/planetsuperheroes/staticfiles
    depends_on:
      - web
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  static_volume:
