version: '3.8'

services:
  web:
    build: .
    command: gunicorn universidad.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/planetsuperheroes
      - static_volume:/planetsuperheroes/staticfiles
    expose:
      - 8000
    env_file: .env
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/planetsuperheroes/staticfiles
    depends_on:
      - web
    networks:
      - default

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  static_volume:
  postgres_data:


