INSERT INTO `planetSuperheroesDB`.`categories` ( name) VALUES (  'Marvel'), ( 'DC');

-- Insertar valores en products
INSERT INTO `planetSuperheroesDB`.`products` (name, description, price, discount, stock, image, pages, format, weight, isbn, category_id, calification)
VALUES 
('Capitan America',
 'El primer año de la revolucionaria etapa que devolvió toda su gloria al Centinela de la Libertad. Después de que fuera dado por muerto por los suyos, el Capitán América ha regresado. Sin su escudo y sin sus amigos, tendrá que afrontar la lucha contra Hydra, al tiempo que aparece ante sus ojos el plan de los Skrull para dominar el planeta. El guionista Mark Waid, junto a los genios del dibujo Ron Garney (Lobezno: Arma X) y Andy Kubert (Marvel 1602), comanda esta brillante etapa del Capitán América. Contiene la traducción de los comic books originales Heroes Return: Captain America números 1 al 12 publicados en USA por Marvel Comics. Volumen único.',
 9800.00,
 30,
 64,
 '/assets/images/marvel-capitanAmerica.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Daredevil Comic',
 '¡El hombre sin miedo desapareción! Daredevil ya no está más en Hells Kitchen, y en su ausencia, los verdaderos demonios salen a jugar. El detective cole North cree que detuvo a Daredevil, pero esta es solo la antesala para más problemas. Matt Murdock es un hombre cambiado, pero... ¿su cambio fue para mejor o para peor? ¡Acaso puede vivir una vida sin su alter ego? ¡Continúa la emocionante saga de Daredevil de Chip Zdarsky!',
 3040.00,
 10,
 120,
 '/assets/images/DareD.png',
 120,
 '26x17x2cm',
 0.45,
 '9786075688336',
 1,
 NULL),
('Dead Pool Comic',
 'Es una historia de amor, Deadpool, ¡solo di que sí! Elsa Bloodstone, la cazadora de monstruos, está muriendo, y el único que puede salvarla es… ¡Wade Wilson! ¿Qué salió mal con la mística y mágica gema Bloodstone de Elsa? ¿Qué puede hacer Deadpool al respecto? ¿Y cuál es la verdad real de la maldición Bloodstone? Te esperan escándalo, traición y una dimensión llena de horrible sustancia viscosa. ¡Se va a poner complicado! ¡Entonces, el Rey de los Monstruos se enfrenta al Rey de los Dragones! Una secta antigua y malvada quiere matar a Deadpool. Un antiguo dios del espacio malvado quiere matar a Deadpool. ¿¡¿Por qué todos quieren matar a Deadpool?!',
 9800.00,
 10,
 64,
 '/assets/images/marvel-deadpool.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Flash: Flashpoint',
 '¡Todo lo que Barry Allen conoce ha cambiado en un instante! Flash es el hombre más rápido del mundo, pero este no es su mundo. El curso de la historia ha cambiado y una nueva realidad ha reemplazado a la suya. Su madre está viva, sus seres queridos son extraños y sus amigos cercanos han cambiado, se han ido o peor. En un mundo al borde de una guerra cataclísmica, ¿dónde están los mejores héroes de la Tierra para detenerla?',
 9800.00,
 30,
 240,
 '/assets/images/dc-flash.jpg',
 240,
 '20x29x2cm',
 0.60,
 '978-987-819-167-6',
 2,
 NULL),
('Ironman: The invincible',
 'Con un trozo de metralla incrustado en su pecho, peligrosamente cerca del corazón, lo único que mantiene con vida al multimillonario Tony Stark es su supertraje de hierro. Desafortunadamente para los villanos, también lo convierte en un arma devastadora contra el mal. Sus batallas contra algunas de las amenazas más grandes del cómic se cuentan en este volumen de 192 páginas con imágenes icónicas de Iron Man y un texto del legendario Roy Thomas, autor de 75 Years of Marvel Comics: From the Golden Age to the Silver Screen.',
 9800.00,
 30,
 64,
 '/assets/images/marvel-ironMan.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Justice League: The New 52',
 'El título insignia del relanzamiento de New 52 de DC, Justice League busca definir el nuevo DC Universe con historias y personalidades de personajes modificadas, sorpresas narrativas y una apariencia modernizada y optimizada, y DC ha aprovechado su mayor talento para hacerlo. Los guiones prolíficos hasta el punto de la ubicuidad de Johns en una escala enorme para volver a presentar el elenco a los lectores y entre ellos mientras primero chocan y luego se unen contra el omnipotente Darkseid. El escalofrío entre el obsesivamente disciplinado Batman y el despreocupado Green Lantern, el trágico origen del nuevo Cyborg en la liga y las insinuaciones de un Superman más peligroso (tal como se explora con estilo subversivo en la espectacular Action Comics de Grant Morrison) ayudan a dar un modesto grado de profundidad a la vertiginosa narrativa. Mientras tanto, Lee, que define una época, hace lo suyo, creando paisajes urbanos increíblemente detallados y personajes hermosos, aunque algo homogéneos, para representar la destrucción cataclísmica. Este es un título de gran éxito que no muestra signos de desaceleración. Merece un lugar en las estanterías como, para bien o para mal, la quintaesencia del cómic de superhéroes contemporáneo.',
 9800.00,
 30,
 64,
 '/assets/images/dc-justiceLeague.jpg',
 64,
 '20x29x2cm',
 0.60,
 '1401237886',
 2,
 NULL),
('Spiderman',
 'Un gigantesco volumen, que reúne tanto Universo Spiderman como Spidergedón, las dos grandes sagas dedicadas a unir a todos los Hombres y Mujeres Araña, con sus respectivos cruces. En primer lugar, Dan Slott (El Asombroso Spiderman) y Olivier Coipel (Dinastía de M) se unen para ofrecerte el mayor evento en la historia de Spiderman. Más peligroso que nunca, Morlun amenaza a todos los Hombres Araña que existen en el Multiverso, pero esta vez no está solo: tiene a la familia a su lado. ¡Todos los Spiderman que han existido están en peligro! A continuación, Los Herederos han escapado y planean acabar con todas las arañas que existen. Será necesario un ejército para hacerlos frente. Spiderman, Octopus, Spider-Gwen, Miles, Spiderwoman, el Spiderman de PS4... y todos los demás estarán aquí. Contiene la traducción de los comic books originales Edge of Spider-Verse números 1 a 5, FCBD 2014: GotG, The Amazing Spider-Man números 4 y 7 a 15, Spider-Verse números 1 a 2, The Superior Spider-Man números 32 a 33, Spider-Man 2099 números 5 a 8, Scarlet Spiders números 1 a 3, Spider-Woman números 1 a 4, Spider-Verse Team-Up números 1 a 3 y Edge of Spider publicados en USA por Marvel Comics.',
 30600.00,
 10,
 300,
 '/assets/images/marvel-spiderman.jpg',
 300,
 '20x29x5cm',
 0.80,
 '9788416998166',
 1,
 NULL),
('Stan Lee meets Spiderman',
 '¡El primero de una serie de especiales independientes que celebran el 65 aniversario del empleo de Stan Lee en Marvel! Primero, Stan y el artista Olivier Coipel presentan un encuentro entre "El Hombre" y su creación de telarañas. Luego, Joss Whedon y Michael Gaydos te llevarán a una convención interdimensional de cómics en el tiempo. Y finalmente, una representación del clásico AMAZING SPIDER-MAN #87 con guión de Stan, en el que Spidey revela su verdadera identidad a sus amigos más cercanos.',
 9800.00,
 10,
 64,
 '/assets/images/marvel-spiderman-amazing.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Supergirl: Brainiac',
 '¡La Tierra está siendo atacada por mil millones de Braniacs! El malvado androide y sus fríos y calculadores clones han engañado a Superman para que se aleje de la órbita de la Tierra, dejando el planeta listo para ser cosechado. Sólo Supergirl tiene posibilidades de frenar el ejército del supervillano. ¿Pero regresará el Hombre de Acero a tiempo para ayudar a su primo menor?',
 9800.00,
 30,
 64,
 '/assets/images/dc-superGirlpg.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 2,
 NULL),
('Superman: The last',
 '¡LAS MEJORES AVENTURAS DEL HOMBRE DE ACERO Y LA PRINCESA GUERRERA! Desde 1940, Wonder Woman ha sido un símbolo de la libertad, la justicia y la igualdad para personas en todas partes del mundo. En estas páginas nos ponemos nuestras tiaras y nuestros brazaletes indestructibles para unirnos al festejo de los ochenta años de la princesa Diana, recorriendo su pasado, presente y futuro. Superman es otro símbolo de la justicia, pero al protector de Metrópolis lo espera un futuro sombrío, donde ha desaparecido a manos de su peor enemigo... ¡uno que nadie espera! Lois Lane, antiguo interés romántico de Clark Kent, cuenta cómo fueron los últimos días del Hombre de Acero, en una aventura que homenajea al primer superhéroe de la historia.',
 4950.00,
 10,
 64,
 '/assets/images/dc-wonderWomen.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 2,
 NULL),
('X-Men comic',
 '¡El amanecer de los mutantes no para de asombrar! Fuera de Krakoa, Domino tiene una misión: encontrar a la persona que, de alguna forma, le está robando sus poderes... ¡antes de que se le acabe la suerte! Los Marauders todavía no asimilan lo drástico de su última pérdida. Y, por su parte, Wolverine continúa su cruzada imposible contra el Cartel de las Flores. Además: un capítulo especial de Jean Grey y Emma Frost que te dejará sin palabras.',
 9800.00,
 30,
 64,
 '/assets/images/marvel-xmen.jpg',
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Black Widow',
 'La historia de espías del siglo! Natasha Romanoff es la espía más letal del Universo Marvel y el corazón palpitante de los Avengers. Pero cuando una figura misteriosa comienza a explotar su turbio pasado, ¡Black Widow debe pasar a la clandestinidad y desaparecer del mapa! ¿En quién puede confiar en esta red de engaños? Y lo que es más importante, ¿pueden sus amigos seguir confiando en ella? Natasha debe analizar todos los nombres de su pasado, ¡comenzando con Tony Stark y Bucky Barnes! Black Widow y el Soldado del Invierno tienen una gran historia, pero cuando se reúnan, pueden terminar sin futuro. Su compañera Yelena Belova llama a su puerta, pero, ¿puede ayudar a Natasha a superar su pasado? Y cuando Black Widow apunte a Hawkeye, ¡ella podría recibir un disparo en el corazón!',
 9800.00,
 30,
 50,
 '/assets/images/marvel-blackwidow.jpg',  
 64,
 '20x29x2cm',
 0.60,
 '9788416998166',
 1,
 NULL),
('Batman: Rebirth',
 'Todo comienza cuando Batman encuentra en su cuartel general un objeto que los seguidores de DC Comics conocen perfectamente: un botón ensangrentado. Pero ¿cómo ha llegado ahí el objeto con el que empezó la trama de Watchmen? El Caballero Oscuro, el mejor detective del mundo, pide ayuda a Flash, el mejor policía forense del planeta, para resolver un misterio que recorre el espacio y el tiempo. ¿Quién habrá dejado ahí ese regalo envenenado? Lo cierto es que están a punto de averiguarlo, ya que la batcueva va a recibir una visita que catalizará una aventura crucial de estos dos héroes que también tendrá una gran importancia en el futuro inmediato de todo el Universo DC.',
 9800.00,
 30,
 15,
 '/assets/images/dc-batman.jpg',
 64,
 '20x29x2cm',
 0.55,
 '978-987-819-184-3',
 2,
 NULL);


-- Insertar roles
INSERT INTO `planetSuperheroesDB`.`roles` (name)
VALUES
('User'),
('Vendedor'),
('Admin');



INSERT INTO `planetSuperheroesDB`.`mycomicapp_user` (email, first_name, last_name, password, address, phone, image, date_joined, is_active, is_staff, is_superuser, role_id) 
VALUES 


('duncang@gmail.com', 'Roni Duncan ', 'Martinez', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '246 Pine St', 123456789, 'eva_williams.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('vargasveronica.ar@gmail.com', 'Veronica', 'Vargas', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '789 Elm St', 123456789, 'alice_smith.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('emirobles@gmail.com', 'Emilce', 'Robles', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '101 Oak St', 123456789, 'bob_johnson.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('escuelamedia86@gmail.com', 'Jorge', 'Pegoraro', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '246 Pine St', 123456789, 'eva_williams.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('pameponce1@gmail.com', 'Pamela', 'Ponce', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '246 Pine St', 123456789, 'eva_williams.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('gonzaloolmedo1@gmail.com', 'Gonzalo', 'Olmedo', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '246 Pine St', 123456789, 'eva_williams.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('velezpaula.a@gmail.com', 'Paula', 'Velez', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '456 Main St', 123456789, 'joan_doe.jpg', '2024-05-23 16:00:04', true, true, false, 2), 
('marcovirinni@gmail.com', 'Marco', 'Virinni', 'pbkdf2_sha256$600000$5AckuCNmyCM6lgLATnfxT8$nljFWwLfJnCPMsUYzrM2bmGsQdUNIraa18TdPPuJnmU=', '123 Main St', 123456789, 'https://res.cloudinary.com/dbz5bknul/image/upload/v1710547090/marco_virinni_oov5tk.jpg', '2024-05-23 16:00:04', true, true, false, 2), 



('developers-superheroes@gmail.com', 'Develop', 'Team','pbkdf2_sha256$600000$TM6SUusGx9g4tG3ixjFULr$2D2mz/i5G1/1mEx4bhuIm6NKwPqmg3ZafjD0KD9SLFA=', 'localhost', 123456789, 'michael_brown.jpg', '2024-05-23 16:00:04', true, true, true, 3);


INSERT INTO `planetSuperheroesDB`.`orders` (user_id, state, order_date, payment_method, shipping_method, payment_status, total_amount)
VALUES
(1, 'En Proceso', '2023-09-25', 'Tarjeta de credito', 'Envio expres', 'Aprobado', 200.00),
(2, 'Cancelado', '2023-09-26', 'PayPal', 'Envio estandar', 'Cancelado', 150.00),
(3, 'Completado', '2023-09-27', 'Tarjeta de credito', 'Envio estandar', 'Completado', 95.00),
(4, 'En Proceso', '2023-09-28', 'PayPal', 'Envio expres', 'Aprobado', 300.00),
(5, 'Completado', '2023-09-29', 'Tarjeta de credito', 'Envio estandar', 'Aprobado', 180.00),
(6, 'Cancelado', '2023-09-30', 'PayPal', 'Envio estandar', 'Cancelado', 9800),

(1, 'En Proceso', '2023-09-25', 'Tarjeta de credito', 'Envío expres', 'Aprobado', 200.00),
(2, 'Cancelado', '2023-09-26', 'PayPal', 'Envio estandar', 'Cancelado', 150.00),
(3, 'Completado', '2023-09-27', 'Tarjeta de credito', 'Envio estandar', 'Completado', 95.00),
(4, 'En Proceso', '2023-09-28', 'PayPal', 'Envio expres', 'Aprobado', 300.00),
(5, 'Completado', '2023-09-29', 'Tarjeta de credito', 'Envio estandar', 'Aprobado', 180.00),
(6, 'Cancelado', '2023-09-30', 'PayPal', 'Envio estandar', 'Cancelado', 9800);

INSERT INTO `planetSuperheroesDB`.`order_items` (quantity, product_id, order_id)
VALUES
(3, 1, 1),
(2, 2, 2),
(1, 3, 3),
(2, 4, 4),
(4, 5, 5),
(1, 6, 6),

(1, 6, 7),
(3, 5, 8),
(2, 4, 9),
(1, 3, 10),
(3, 2, 11),
(2, 1, 12);
